"""rename refresh_tokens.token to token_hash

Revision ID: 7b6248d15139
Revises: c86cbe7aa76b
Create Date: 2026-09-16 17:15:31.101932

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b6248d15139"
down_revision: Union[str, Sequence[str], None] = "c86cbe7aa76b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "refresh_tokens", sa.Column("token_hash", sa.String(length=64), nullable=False)
    )
    op.alter_column(
        "refresh_tokens",
        "token",
        existing_type=sa.VARCHAR(length=512),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.create_unique_constraint(None, "refresh_tokens", ["token_hash"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("refresh_tokens_token_key", "refresh_tokens", type_="unique")
    op.alter_column(
        "refresh_tokens",
        "token",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=512),
        existing_nullable=False,
    )
    op.drop_column("refresh_tokens", "token_hash")
    # ### end Alembic commands ###
